export const GET_BUSINESSES = 'GET_BUSINESSES';
export const ADD_BUSINESS = 'ADD _BUSINESS';
export const DELETE_BUSINESS = 'DELETE _BUSINESS';
export const SET_CURRENT = 'SET _CURRENT';
export const CLEAR_CURRENT = 'CLEAR _CURRENT';
export const UPDATE_BUSINESS = 'UPDATE _BUSINESS';
export const FILTER_BUSINESSES = 'FILTER_BUSINESSES';
export const CLEAR_BUSINESSES = 'CLEAR_BUSINESSES';
export const CLEAR_FILTER = 'CLEAR _FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const BUSINESS_ERROR = 'BUSINESS_ERROR';


